### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [gsmental/DevToolKit#1]
H, @gsmental, i design logos to contribute to open source projects. I have an idea for this project. If you want, I'd like to show you the logo. i will wait feedback. Have a nice day.

**Comment by gsmental** [comment]
ok. show me

**Comment by reallinfo** [comment]
couldn't decide the color. If you like it, you can help with about the color.

**Comment by reallinfo** [comment]
![tdk](https://user-images.githubusercontent.com/36298335/54480148-002e9f00-4836-11e9-8148-90201b3125b9.jpg)

**Comment by reallinfo** [comment]
EDIT: I forgot to tell you. It also represents code icon enhancement. 

![dt](https://user-images.githubusercontent.com/36298335/54539744-c2ea1e80-49a7-11e9-92c8-f43dda6286f1.jpg)

**Comment by gsmental** [comment]
is it free of paid icon

**Comment by gsmental** [comment]
https://informme.in/

https://informme.in/assets/logos/IM64BlueBackground.png
this is my logo for my website. 
i need logo between <> symbols like u designed it as above

**Comment by reallinfo** [comment]
of course free. if you like it I can send a pr at the end of this job.

**Comment by reallinfo** [comment]
Hi again, Would you like to resume the issue?

**Comment by gsmental** [comment]
hi bro, i need a logo 

a child Dinosaur  reading a book, can u provide me, it will be used for commercial purpose
